name: Generate Contribution Snake

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"  # every 12 hours

# grant write permission to contents so we can push to output branch
permissions:
  contents: write

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snake svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ankita1477
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & push to output branch
        run: |
          set -e
          ls -al dist
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan output
          git --work-tree=dist add --all
          git commit -m "chore: update snake animation $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          git push -f origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
